- src/collection_impls.rs
`enum_set` was moved to libcollections crate, which is unstable and we shouldn't depend on it.
(As suggested in https://github.com/rust-lang/rustc-serialize/pull/14#issuecomment-68669064)
> Drop support for `enum_set`

- src/json.rs
- src/serialize.rs
a few nits from the rust repository got in there, too.
> encoding non string key map to json silently produces invalid json instead of failing

- src/json.rs
first getting https://github.com/rust-lang/rust/issues/21470 fixed here, will PR to rust repository later
this is only a partial fix.
> don't ignore encoder failures in json::encode

- src/json.rs
merge after #31 
closes https://github.com/rust-lang/rust/issues/21470 here
> Allow enum variant as hashmap key

- src/json.rs
This makes the library build again and all tests pass as of `rustc 1.0.0-dev (d77f6d536 2015-01-27 11:07:26 +0000)`
> Update to rust master (io -> old_io)

- src/json.rs
Closes #40 
It's very useful in libraries like [valico](https://github.com/rustless/valico) or [queryst](https://github.com/rustless/queryst) which work with mutable JSON structures.
> Add `as_object_mut` and `as_array_mut` functions

- src/json.rs
- src/lib.rs
Make JSON module compatible with the new IO crate.
> use new IO crate

- src/json.rs
> change panic to failure when parser-stack depleted

- src/json.rs
There is one failure left in `cargo test` because of rust-lang/rand#21
> Upgrade to rustc 1.0.0-nightly (fed12499e 2015-03-03) (built 2015-03-04)

- src/serialize.rs
These no-op implementations are useful deriving implementations for something that contains such a marker.
> Implement Decodable and Encodable for std::marker::PhantomData;

- src/json.rs
In accordance with standard JSON string is a sequence of zero or more Unicode characters (except `"` or `\` or **control character**) and backslash escapes. This pull request forbids the use of unescaped control characters within a string.
> Control characters inside string should be forbidden

- src/json.rs
Sometimes it is necessary to decode big sequence of Unicode hex escapes, like:
```
"\uF975\uf9bc\uF9A0\uF9C4\uF975\uf9bc\uF9A0\uF9C4..."
```
Texts with non-Latin characters usually look like this. This PR accelerates the decoding of such strings by 25%.
```
Before: test json::tests::bench_decode_hex_escape ... bench:      4295 ns/iter (+/- 176)
After: test json::tests::bench_decode_hex_escape ... bench:      3200 ns/iter (+/- 148)
```
> Improve decoding of hex escapes

- src/serialize.rs
std::os::windows::OsStringExt moved to std::os::windows::ffi::OsStringExt.
> Update to rustc 1.0.0-dev (e46610966 2015-03-17) (built 2015-03-17)

- README.md
Might help out people just coming to Rust.  Might be a little bit of a deep dive trying to find out why the original statement doesn't work with the latest nightlies.
> Fixed the README with respect extern crate.

- Cargo.toml
- src/lib.rs
- src/serialize.rs
rustc-serialize is one of the most heavily depended upon crates; 125 reverse dependencies when I last checked. Getting it compiling on the beta channel will make it a lot easier to get other crates that depend on it compiling on the beta channel.
To do so, we need to remove its dependency on the `convert` feature, which is waiting on rust-lang/rfcs#529 that seems to be in rapid development. We can do that by just reverting the commit that adds support to this feature, and then add it back later once convert is no longer feature-gated.
The other fix is to simply update the dev dedpendency on `rand`, to a newer version that depends on a newer `log`. `log` also doesn't quite build on beta channel yet, but there is already a commit in the repository that fixes that (rust-lang/log@93fac65cd), …
> Beta fixes

- src/serialize.rs
Introduced in #87
Better continuous integration would be great. It's the second time in three days that one of the official crates doesn't compile on Windows.
> Fix compilation error on Windows

- src/json.rs
I was wondering why my code was printing numbers to stdout, only to find out it came from here.
> Remove what looks like a relicate

- src/serialize.rs
If we had support for using more specific impls, we could add a blanket
encode/decode for all types implimenting Deref<Target=Encodable> (and
similar for Decodable), but for now this will do.
> Support encode/decoding Cow in the same way as Rc, a plain passthrough

- benches/base64.rs
- src/base64.rs
Iterators are really fast. So is using mutation instead of pushing.
Before:
test bench_to_base64         ... bench:       356 ns/iter (+/- 10) = 424 MB/s
test bench_to_base64_large   ... bench:     21378 ns/iter (+/- 1030) = 467 MB/s
After:
test bench_to_base64         ... bench:       207 ns/iter (+/- 10) = 729 MB/s
test bench_to_base64_large   ... bench:     10900 ns/iter (+/- 709) = 917 MB/s
[Diff best seen ignoring whitespace.](https://github.com/rust-lang/rustc-serialize/pull/119/files?w=1)
> Speed up base64 encoding 2x by using mutating iterators and better preallocation

- src/json.rs
New Rust users often use rustc-serialize simply because it's the official package and they never heard of Serde. Mentioning Serde in rustc-serialize docs will allow them to consider a more efficient and feature-wise package.
One use case is people coming to test Rust performance and seeing it as a slow language because they're using an older JSON package (cf. http://www.reddit.com/r/rust/comments/38s1n3/why_is_rust_much_slower_and_memory_consuming_than/).
> Mention Serde in rustc-serialize docs

- src/json.rs
- src/serialize.rs
This change fixes #114.
I was running into the same issue, and noticed that PhantomData's implementation of `encode` was just returning `Ok`, even though it was not actually emitting anything. This caused the outputted JSON to have an invalid syntax.
> added fix for encoding and decoding phantom data

- src/collection_impls.rs
As found [on Stack Overflow](http://stackoverflow.com/q/32331120/155423)
> BTree{Map,Set}s do not require PartialEq, only Ord

- src/base64.rs
Check for an empty length when calculating the number of lines in the input to prevent the arithmetic overflow panic. 
Fixes #143.
> Prevent arithmetic overflow in to_base64 when specifying line_length

- src/json.rs
If one tries to parse negative zero with `Json::from_str()`, computing the 2's complement of zero causes an arithmetic overflow. Check for this condition before computing the 2's complement and just return zero, since that is the 2's complement of zero anyway.
Fixes #109
> Correct parsing of negative zero

- src/json.rs
> Return a SyntaxError instead of panicking on invalid input

- src/collection_impls.rs
- src/lib.rs
- src/serialize.rs
For instances where the length of a collection must be obeyed, but is
untrusted, calls to with_capacity() could result in OOM errors.
This change makes it so that collections don't pre-allocate more than
1MB of memory.
> Cap calls to with_capacity with sane default

- src/serialize.rs
While attempting to understand the [dbus-serialize](https://github.com/srwalter/dbus-serialize) module, I discovered that the main traits in this module are not documented. So I wrote some documentation.
> Document the core traits

- src/serialize.rs
In the documentation of the Encodable and Decodable traits, encourage users to
let the compiler implement the traits for them.
(I only just found out about the compiler support, which is why this wasn't in my last PR).
> Push use of derive(RustcEncodable,RustcDecodable)

- src/json.rs
Allows a the destructuring of a Json type with move semantics.
For example,
```rust
let json_value = Json::from_str("{}").unwrap();
let json_object = (|json: Json| {
// doesn't compile
json.as_object()
})(json_value);
assert!(json_object.is_some());
```
if a Json type is passed to a closure, or some other scope block, when trying to destructure it, there is a lifetime conflict. The Json given as a parameter to the closure was moved, but it cannot be moved out of the closure as an Object.
If you replace as_object with into_object, the Object value returned is not a reference, so it can be moved out of the scope.
But this works,
```rust
let json_value = Json::from_str("{}").unwrap();
let json_object = (|json: Json| {
json.into_object()
})(json_value);
assert!(json_object.is_some());
```
> added into_* variations for as_object, as_array

- src/json.rs
Makes writing serialization tests easier
> EncoderError: derive PartialEq

- src/serialize.rs
On a platform that does not set cfg(unix) or cfg(windows), the impl blocks modified in this PR are left empty, causing compilation to fail
This fixes compilation by not attempting to implement Encodable or Decodable on Path or PathBuf on platforms without the OsStr and OsString conversion functions.
> Fix for building on Redox

- src/base64.rs
- src/hex.rs
I was trying to use the Hex and Base64 traits with generics and that just didn't work for me.
After some digging around and learning a bit about Sized, I was able to find the solution to my problem.
I saw the needed implementation already existed in [serialize.rs for Encodable](https://github.com/rust-lang-nursery/rustc-serialize/blob/6488e2b61fa7d6ed7b7ca1028316db0ea40af861/src/serialize.rs#L1105), so I added the missing pieces of code to both Hex and Base64.
Here's a small example of usage, to show what was missing.
```
extern crate rustc_serialize;
use rustc_serialize::hex::{ToHex, FromHex, FromHexError};
use rustc_serialize::base64::{ToBase64, FromBase64, FromBase64Error};
use rustc_serialize::base64;
fn hex_to_base64<T: FromHex>(buf: &T) -> Result<String, FromHexError> { …
```
> implementations with ?Sized for Hex and Base64 traits

- src/serialize.rs
This is a new future incompatibility warning, "patterns aren't allowed
in methods without bodies".
> Fix patterns_in_fns_without_body warning

- src/serialize.rs
I ran into this when migrating from `(), (usize, ), (usize, usize)` and so on to fixed size arrays. The generic code ends up using `[usize; 0]` as its smallest case.
The [T; 0] case could be implemented without trait bound for T, but it didn't seem to really matter, symmetry with the other array cases seems good.
> Implement serialization of [T; 0]

- src/serialize.rs
This is a minor change to match the way that the `libc` and `rand` crates now have checking for Redox. It is more accurate than checking for `cfg(redox)`.
> More precise identification of Redox target

- src/json.rs
As the precision of a floating point number depends
on its magnitude, adding each fractional digit to a large
number accumulates the floating point error quite quickly.
The error is accumulated much slower when assembling
the fractional part separately and then finally adding it
to the large number. Vide: the added test cases.
> decrease rounding error when parsing f64 from JSON

- src/base64.rs
Previously, hoedown did not understand that this was an example. pulldown-cmark does. This fixes the example to be compile-able.
Fixes https://github.com/rust-lang/rust/issues/40994
> Fix example to compile

- src/base64.rs
- src/hex.rs
This was introduced in https://github.com/rust-lang-nursery/rustc-serialize/commit/49d4958b2e88335e586b18734ee1ae1cde5e0da1#diff-afe95bd2eae65804dddefc843cd57bb5R126, `0u8` was mistakenly replaced by `08` instead of `0`.
Due to luck, this mistake does not have any consequences, but it is still confusing when reading the code.
> Fix automated code update mistake

- src/serialize.rs
Allows us to publish a patch version which still compiles after https://github.com/rust-lang/rust/pull/117984 fixes a type system soundness regression.
> fix the `implied_bounds_entailment` lint
