rust-lang-deprecated/rustc-serialize

src/json.rs
`json::from_reader` -> `json::Json::from_reader`
`json::from_str` -> `json::Json::from_str`
I personally don't see a reason why the struct constructors should be
disjoint from the struct itself.
[breaking-change]
=> Make constructor functions into static methods

src/base64.rs, src/hex.rs, src/json.rs
- deriving -> derive
- fix for fmt changes
=> Updated to master

src/json.rs
* enum_set moved to collections,
* from_str deprecated.
=> Update to rustc master

src/collection_impls.rs, src/json.rs, src/lib.rs, src/serialize.rs
I don't even anymore just let my code build already please
=> Copy pasta sync update

src/base64.rs, src/hex.rs, src/json.rs, src/lib.rs, src/serialize.rs
This is the immediate fallout of recent rustc changes.
=> Remove old Sized? bounds and feature gates.

Cargo.toml, src/base64.rs, src/collection_impls.rs, src/hex.rs, src/json.rs, src/lib.rs, src/serialize.rs
=> Prep for alpha

README.md
Looks like this fell out of date!
=> Derive not Deriving

src/base64.rs, src/hex.rs, src/json.rs
=> update to recent rust changes: see rust-lang/rust#21457

src/serialize.rs
Please publish this on crates.io?
=> Work around the std::path reform.

src/json.rs
Update this, before somebody spends an hour trying to figure out what the fudge...
=> Fix documentation: types

src/json.rs
Link to rustc commit: rust-lang/rust@bc9084b
=> Switch std::fmt::{Writer to Write} for compatibility with latest Rustc (6c065fc8c)

src/json.rs
Same as https://github.com/rust-lang/rust/pull/21314 but for rustc-serialize instead of serialize.
=> Use singular they in json docs

src/base64.rs, src/hex.rs, src/json.rs, src/serialize.rs
r? @alexcrichton while I'm here
=> Attribute cleanup

src/serialize.rs
See https://github.com/rust-lang/rust/commit/542e2bb
=> Fallout from `os` stabilization

src/json.rs
Implement `From<io::Error>` for `ParserError` and `From<ParserError>`
for `DecoderError`.
I considered implementing `From<io::Error>` for `DecoderError` as well,
as a convenience for mapping it through `ParserError`, but that seems
less obviously useful.
=> Implement std::convert::From for the json Error types

src/json.rs
Remove leading newlines; replace lines containing only whitespace with empty lines; replace multiple trailing newlines with a single newline; remove trailing whitespace in lines.
This PR was created semiautomatically.
=> Clean whitespace

src/json.rs
http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf
> All characters may be placed within the quotation marks except
> for the characters that must be  escaped:
> quotation mark (U+0022), reverse  solidus  (U+005C),
> and  the  control  characters  U+0000  to  U+001F.
https://tools.ietf.org/html/rfc7159#section-7
> All Unicode characters may be placed within the quotation marks,
> except for the characters that must be escaped:
> quotation mark, reverse solidus, and the control characters
> (U+0000 through U+001F).
`char::is_control` returns whether a code point is in Unicode General Category Cc, which includes more than C0.
=> Only "C0" control characters are excluded in strings.

src/json.rs, src/serialize.rs
`Encodable` and `Decodable` traits.
=> Add trait implementation for `Result<T, E>`

src/lib.rs
r? @alexcrichton 
If this lands, could we get a version bump please?
=> Add rustbuild boilerplate

README.md
=> Fix documentation dead link
